### ISSUE TITLE
Расширение нагрузочных тестов

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#103]
1) WSDataGetUser - чтение данных через веб-сокеты
2) несколько значений для тега в пакете данных при запросе на запись данных

**Comment by zippy-junior** [comment]
![Screenshot from 2023-08-02 13-53-11](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/87cefd9e-43a7-4451-8ff7-dbd1e896bbe1)
![Screenshot from 2023-08-02 13-53-30](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/7055de1d-0333-489f-91e2-dfc2757fc63a)
![Screenshot from 2023-08-02 13-53-36](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/b13fe47d-946c-4379-bdd1-747f8f66ddce)

**Comment by Vovaman** [comment]
При посылке сообщения через websocket формат запроса расширяется: добавляется ключ "action".
Пример:
{
    "action": "set",
   "data": {основное тело запроса}
}

**Comment by zippy-junior** [comment]
![Screenshot from 2023-08-03 10-37-53](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/5236d889-e219-4e48-a4e2-0799c7c1f551)
![Screenshot from 2023-08-03 10-40-04](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/d7f2698c-07d8-48a6-9b0e-c572b861be39)
![Screenshot from 2023-08-03 10-40-31](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/1e84d87c-453f-40ea-8bcf-0003dd27c246)

**Comment by zippy-junior** [comment]
При проведении остальных тестов WSDataSetUser, WSDataGetUser, DataGetUser, ошибки не возникает и тест проходит нормально. При приведении теста DataSetUSer идет 100% потеря запросов. Код для формирования пакета для DataSetUser идентичен с WSDataSetUser. Docker логи не выдают ошибок со стороны сервисов.

**Comment by Vovaman** [comment]
при формировании запроса через http в запросе не должно быть ключа "action", потому что действие определяется через тип запроса (POST - это set, GET - это get). ключ "action" нужен только при связи через websocket, потому что в этом случае один канал на все запросы
