### ISSUE TITLE
Ошибка при чтении данных нода в иерархии

### ISSUE THREAD

**Issue by zippy-junior** [mp-co-ru/mpc-peresvet#114]
При запросе данных нода коннектора формата
{
    "id": ",,,,"
}
Появляется ошибка в файле базового класса model_crud_svc.py:
mes_data["filter"]["objectClass"] = [self._config.hierarchy['class']]
TypeError: NoneType object does not support item assignment 

![photo_5382185954736982665_w](https://github.com/mp-co-ru/mpc-peresvet/assets/72471805/91970e71-901a-464f-b0e7-be90946a9452)

**Comment by Vovaman** [comment]
Дублирует #113
