### ISSUE TITLE
Ошибка при создании дублирующегося объекта

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#198]
Если сделать 2 попытки создания объекта с одинаковым именем, то при второй попытке возникает ошибка:
![image](https://github.com/mp-co-ru/mpc-peresvet/assets/11216787/e4a35c89-5d32-4068-a91b-5bcccd3bb6af)

Тело запроса: {"attributes":{"cn": "Area 11"}}

**Comment by Vovaman** [comment]
В результате клиент должен получать ошибку
А в консоли никакого трэйсбэка быть не должно

**Comment by VVB-Github** [comment]
формат изменен. Не до конца известно как избавиться от ключа detail
