### ISSUE TITLE
PostgreSQL connection pool

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#22]
Разобраться с созданием пула коннектов к PSQL (файл psql.py, строка 116).
По умолчанию пул создаётся из 10 коннектов, этого мало для обработки большого количества запросов.
При изменении количества коннектов в пуле необходимо также изменить конфигурацию самого PSQL, чтобы он мог проглотить столько коннектов.
Таким образом: 
1) понять процедуру, как будем настраивать количество коннектов в пуле. (учесть то, что каждый инстанс платформы делает свой пул коннектов). 
2) разогнать нагрузочный тест реальной работы системы, увеличив количество коннектов в пуле
3) попробовать создать рекомендацию по настройке количества коннектов в пуле в зависимости от масштаба системы, а также учесть, по возможности, и другие параметры оптимизации PSQL

**Comment by zippy-junior** [comment]
Запуск теста:
1. Запуск скрипта run_locust_real_job.sh.
2. Остановка всех созданных контейнеров внутри стека mpc-peresvet.
3. Запуск отдельно контейнера ldap_load_test. 
4. Вход в контейнер ldap через Jxplorer и удаление всего дерева нодов.
5. Импорт новой схемы через Jxplorer.
6. Запуск отдельно контейнера postgres и ожидание лога "Database is ready to receive connections".
7. Запуск всех остальных контейнеров.
8. Ожидание индексации базы данных и ldap у всех инстансев peresvet.
9. Вход в панель тестирования locust localhost:8089.
10. 10 пользователей, 2 секунды, http://nginx в качестве настроек теста.
11. Запуск теста.
