### ISSUE TITLE
Изменение тега

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#272]
Запрос изменения тега PUT:
```
http://peresvet/v1/tags/
```
```
{
    "id": "2beaa2d2-725f-103e-924c-a5021ec2dae1",
    "attributes": {
        "prsStep": true
    }
}
```
Не отрабатывает. Флаг prsStep у тега не меняется.

**Comment by VVB-Github** [comment]
проблема решается добавлением поля в `class NodeAttributes`, но не понятно что там указать в title и description

**Comment by Vovaman** [comment]
При создании тега указание prsStep = true отрабатывает верно. Видимо, дело не в NodeAttributes

**Comment by VVB-Github** [comment]
я изменил NodeAttributes и заработало (в обновлении)
