### ISSUE TITLE
Привязка тега к коннектору

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#288]
PUT http://localhost/v1/connectors/
```json
{
    "id": "c499c006-5713-103e-8ecd-3fe5f90074ec",
    "linkTags": [
        {
            "tagId": "eafc3fdc-725f-103e-924f-a5021ec2dae1",
            "attributes": {
                "prsJsonConfigString": {"type": "C", "address": 3, "count": 1, "slave": 0},
                "description": "Work"
            }
        }
    ]
}
```

в результате у узла, описывающего новый привязанный тег, не заполнился атрибут ``description``:
![Screenshot_20240401_175654](https://github.com/mp-co-ru/mpc-peresvet/assets/11216787/8410436b-bddb-40b4-8911-997e56325101)

**Comment by VVB-Github** [comment]
Когда мы привязываем тег к коннектору, старый тег остается неизменным - это нормальное поведение?
