### ISSUE TITLE
Обработка ошибок во всех CRUD-командах

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#311]
По типу кода, сделанного в рамках задачи #289

**Comment by VVB-Github** [comment]
Сейчас я везде проставляю error_handler-ы. Сейчас я в objects это делаю. Но если в запросе PUT выставить не верный id-шник, запрос бесконечно обрабатывается, что не является корректным поведением. Мне это исправить или проставлять error_handler-ы дальше?
Ошибка - Узел a3839f04-a010-103e-9f61-294275040168 не найден.
Запрос - 
{
    "id":"a3839f04-a010-103e-9f61-294275040168",
    "attributes":{"cn":"object3_new"}
}
Код с ошибкой -
File "/home/prs/work/projects/mpc-peresvet/./src/common/model_crud_svc.py", line 339, in _update
    node_dn = await self._hierarchy.get_node_dn(mes_data['id'])
