### ISSUE TITLE
Бесконечная обработка запроса на обновление обьекта при неверно заданном id

### ISSUE THREAD

**Issue by VVB-Github** [mp-co-ru/mpc-peresvet#317]
Ошибка - Узел a3839f04-a010-103e-9f61-294275040168 не найден.
Запрос -
{
"id":"a3839f04-a010-103e-9f61-294275040168",
"attributes":{"cn":"object3_new"}
}
Код с ошибкой -
File "/home/prs/work/projects/mpc-peresvet/./src/common/model_crud_svc.py", line 339, in _update
node_dn = await self._hierarchy.get_node_dn(mes_data['id'])

**Comment by VVB-Github** [comment]
В objects и methods

**Comment by Vovaman** [comment]
Это общая для всех сервисов ошибка: попытка что-то сделать с узлом, которого нет в иерархии.
Поэтому обработка этой ошибки должна быть в модуле model_crud_svc.py.
Сделать надо так: при запросе на изменение ищем узел в иерархии. Если такого узла нет - возвращаем ошибку.
