### ISSUE TITLE
Создание тега с дублирующимся именем

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#331]
![Screenshot_20240523_133508](https://github.com/mp-co-ru/mpc-peresvet/assets/11216787/e8743ad5-5829-4c74-bb5e-ad1fb4da1994)
должна возвращаться ошибка

**Comment by Vovaman** [comment]
Твои пул-реквесты влил, проверь.

**Comment by VVB-Github** [comment]
![image](https://github.com/mp-co-ru/mpc-peresvet/assets/74117474/09638747-89a3-4fcb-bd85-38c0b0918e15)
Что-то обработчика ошибок не видно, хоть я и в dev переключился

**Comment by VVB-Github** [comment]
![image](https://github.com/mp-co-ru/mpc-peresvet/assets/74117474/8d70a02f-90ba-442d-9357-ec88551c6b91)
Работает
