### ISSUE TITLE
В тег типа json нельзя записать массив

### ISSUE THREAD

**Issue by Vovaman** [mp-co-ru/mpc-peresvet#332]
Не работает (тег 84c85e9c-77c5-103e-9707-739fc6471fc5 - типа json):
![Screenshot_20240529_175108](https://github.com/mp-co-ru/mpc-peresvet/assets/11216787/7dd3ece6-9e91-4ee0-97dc-2bff8c432fab)
Вместо этого приходится писать что-то типа:
![Screenshot_20240529_175206](https://github.com/mp-co-ru/mpc-peresvet/assets/11216787/9014c3a6-a831-41d3-8dea-0d5521959404)
Первый вариант тоже должен прокатывать, потому что просто массив значений - это корректный json

**Comment by VVB-Github** [comment]
Поправил, теперь вроде все нормально функционирует
![image](https://github.com/mp-co-ru/mpc-peresvet/assets/74117474/42f429be-7ffe-45e4-b9bb-06041b507677)
