### ISSUE TITLE
Теги и тревоги не прилинковываются к Хранилищам данных 

### ISSUE THREAD

**Issue by VVB-Github** [mp-co-ru/mpc-peresvet#349]
Пытался отправить следующий запрос POST в сервис dataStorages:
```JSON
{
    "linkTags":[{
        "tagId":"99a8bc4a-b2d4-103e-83ba-b9a6d48c0bf6", 
        "attributes":{
            "cn":"tag1",
            "objectClass":"prsTag"
        }
    }],
    "linkAlerts":[{
        "alertId":"4d440216-c809-103e-8748-05e8cc7fd715",
        "attributes":{
            "cn":"alert1",
            "objectClass":"prsAlert"
        }
    }],
    "attributes":{
        "prsJsonConfigString":"{\"dsn\": \"postgresql://postgres:Peresvet21@psql/peresvet\"}",
        "cn": "dataStorage_test",
        "description": "test_DS"
    }
}
```

Получил следующую ошибку:
ERROR    :: Ошибка создания узла {'action': 'dataStorages.create', 'data': {'parentId': None, 'attributes': {'cn': 'dataStorage_test', 'description': 'test_DS', 'prsJsonConfigString': '{"dsn": "postgresql://postgres:Peresvet21@psql/peresvet"}', 'prsActive': True, 'prsDefault': None, 'prsEntityTypeCode': 0, 'prsIndex': None, 'objectClass': ['prsDataStorage']}, 'linkTags': [{'tagId': '99a8bc4a-b2d4-103e-83ba-b9a6d48c0bf6', 'attributes': {'cn': 'tag1', 'prsStore': None, 'objectClass': 'prsTag'}}], 'linkAlerts': [{'alertId': '4d440216-c809-103e-8748-05e8cc7fd715', 'attributes': {'cn': 'alert1', 'prsStore': None, 'objectClass': 'prsAlert'}}]}}

Причем само хранилище данных было созданно, но без прилинкованных тегов и алертов.

**Comment by Vovaman** [comment]
1) В настоящий момент нельзя создавать хранилище и сразу в этом же запросе передавать прилинкуемые теги и алерты, так как нужно после создания хранилища сначала перезапустить платформу.
Но в доке оставляем описание, как будто можно
2) "objectClass" убрать из описания. в коде я его тоже убрал
