### ISSUE TITLE
Ошибка при создании нового узла Tag

### ISSUE THREAD

**Issue by zippy-junior** [mp-co-ru/mpc-peresvet#73]
При создании нового узла `Tag` с атрибутом `prsMaxLineDev` возникает ошибка `ldap.INVALID_SYNTAX`.
Целочисленное значения атрибута `prsMaxLineDev` при обработке валидатором `pydantic` меняется на вещественное.

**Comment by Vovaman** [comment]
Изменил синтаксис у атрибутов, хранящих вещественные значения.
